apiVersion: v1
kind: Service
metadata:
  name: ansible-server
  labels:
    app: news-app


spec:
  selector:
    app: news-app


  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080


  type: NodePort
